### ISSUE TITLE
Panic from master.go

### ISSUE THREAD

**Issue by araobp** [araobp/nlan#7]
```
$ ./master.sh ptn-bgp
2015/12/29 17:58:21 /root/work/src/github.com/araobp/nlan/etc/ptn-bgp.yaml
2015/12/29 17:58:21 # iBGP/eBGP simulation
#
States:
  - Router: pe1
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe1w
              L2sw: l2swpe1w
            Links:
              LocalIp: {{.pe1}}
              RemoteIps: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.101/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.101/24
          - Id: access
            Nodes:
              Ptn: ptnpe1a
              L2sw: l2swpe1a
            Links:
              LocalIp: {{.pe1}}
              RemoteIps: [{{.ce1}}, {{.ce2}}]
            L2Vpn:
              - Vid: 11
                Vni: 111
                Peers: [{{.ce1}}]
                Ip: 10.201.11.1/24
              - Vid: 12
                Vni: 112
                Peers: [{{.ce2}}]
                Ip: 10.201.12.1/24
      Router:
        Loopback: 10.1.1.1/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.201.11.2
                RemoteAs: 1001
              - Peer: 10.201.12.2
                RemoteAs: 1002
  - Router: pe2
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe2w
              L2sw: l2swpe2w
            Links:
              LocalIp: {{.pe2}}
              RemoteIps: [{{.pe1}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.102/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.102/24
          - Id: access
            Nodes:
              Ptn: ptnpe2a
              L2sw: l2swpe2a
            Links:
              LocalIp: {{.pe2}}
              RemoteIps: [{{.ce1}}, {{.ce2}}]
            L2Vpn:
              - Vid: 11
                Vni: 211
                Peers: [{{.ce1}}]
                Ip: 10.202.11.1/24
              - Vid: 12
                Vni: 212
                Peers: [{{.ce2}}]
                Ip: 10.202.12.1/24
      Router:
        Loopback: 10.1.1.2/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.202.11.2
                RemoteAs: 1001
              - Peer: 10.202.12.2
                RemoteAs: 1002
  - Router: pe3
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe3w
              L2sw: l2swpe3w
            Links:
              LocalIp: {{.pe3}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.103/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.103/24
          - Id: access
            Nodes:
              Ptn: ptnpe3a
              L2sw: l2swpe3a
            Links:
              LocalIp: {{.pe3}}
              RemoteIps: [{{.ce3}}, {{.ce4}}]
            L2Vpn:
              - Vid: 13
                Vni: 313
                Peers: [{{.ce3}}]
                Ip: 10.203.13.1/24
              - Vid: 14
                Vni: 314
                Peers: [{{.ce4}}]
                Ip: 10.203.14.1/24
      Router:
        Loopback: 10.1.1.3/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.203.13.2
                RemoteAs: 1003
              - Peer: 10.203.14.2
                RemoteAs: 1004
  - Router: pe4
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe4w
              L2sw: l2swpe4w
            Links:
              LocalIp: {{.pe4}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
                Ip: 10.200.1.104/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
                Ip: 10.200.2.104/24
          - Id: access
            Nodes:
              Ptn: ptnpe4a
              L2sw: l2swpe4a
            Links:
              LocalIp: {{.pe4}}
              RemoteIps: [{{.ce3}}, {{.ce4}}]
            L2Vpn:
              - Vid: 13
                Vni: 413
                Peers: [{{.ce3}}]
                Ip: 10.204.13.1/24
              - Vid: 14
                Vni: 414
                Peers: [{{.ce4}}]
                Ip: 10.204.14.1/24
      Router:
        Loopback: 10.1.1.4/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.204.13.2
                RemoteAs: 1003
              - Peer: 10.204.14.2
                RemoteAs: 1004
  - Router: rr
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnrrw
              L2sw: l2swrrw
            Links:
              LocalIp: {{.rr}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
                Ip: 10.200.1.105/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
                Ip: 10.200.2.105/24
      Router:
        Loopback: 10.1.1.5/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.101
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.102
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.103
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.104
                RemoteAs: 100
                RouteReflectorClient: true
  - Router: ce1
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce1a
              L2sw: l2swce1a
            Links:
              LocalIp: {{.ce1}}
              RemoteIps: [{{.pe1}}, {{.pe2}}]
            L2Vpn:
              - Vid: 1
                Vni: 111
                Peers: [{{.pe1}}]
                Ip: 10.201.11.2/24
              - Vid: 2
                Vni: 211
                Peers: [{{.pe2}}]
                Ip: 10.202.11.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.1.1/24
            Vhosts: 2
          - Network: 172.22.1.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.1/32
        Bgp:
          - As: 1001
            Neighbors:
              - Peer: 10.201.11.1
                RemoteAs: 100
              - Peer: 10.202.11.1
                RemoteAs: 100
  - Router: ce2
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce2a
              L2sw: l2swce2a
            Links:
              LocalIp: {{.ce2}}
              RemoteIps: [{{.pe1}}, {{.pe2}}]
            L2Vpn:
              - Vid: 1
                Vni: 112
                Peers: [{{.pe1}}]
                Ip: 10.201.12.2/24
              - Vid: 2
                Vni: 212
                Peers: [{{.pe2}}]
                Ip: 10.202.12.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.2.1/24
            Vhosts: 2
          - Network: 172.22.2.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.2/32
        Bgp:
          - As: 1002
            Neighbors:
              - Peer: 10.201.12.1
                RemoteAs: 100
              - Peer: 10.202.12.1
                RemoteAs: 100
  - Router: ce3
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce3a
              L2sw: l2swce3a
            Links:
              LocalIp: {{.ce3}}
              RemoteIps: [{{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 3
                Vni: 313
                Peers: [{{.pe3}}]
                Ip: 10.203.13.2/24
              - Vid: 4
                Vni: 413
                Peers: [{{.pe4}}]
                Ip: 10.204.13.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.3.1/24
            Vhosts: 2
          - Network: 172.22.3.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.3/32
        Bgp:
          - As: 1003
            Neighbors:
              - Peer: 10.203.13.1
                RemoteAs: 100
              - Peer: 10.204.13.1
                RemoteAs: 100
  - Router: ce4
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce4a
              L2sw: l2swce4a
            Links:
              LocalIp: {{.ce4}}
              RemoteIps: [{{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 3
                Vni: 314
                Peers: [{{.pe3}}]
                Ip: 10.203.14.2/24
              - Vid: 4
                Vni: 414
                Peers: [{{.pe4}}]
                Ip: 10.204.14.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.4.1/24
            Vhosts: 2
          - Network: 172.22.4.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.4/32
        Bgp:
          - As: 1004
            Neighbors:
              - Peer: 10.203.14.1
                RemoteAs: 100
              - Peer: 10.204.14.1
                RemoteAs: 100
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xa03ac]

goroutine 1 [running]:
github.com/araobp/nlan/util.ListHosts(0x51ee01, 0x10bebee0)
        /root/work/src/github.com/araobp/nlan/util/etcd.go:78 +0x154
github.com/araobp/nlan/common.ReadState(0x10b256c8, 0x0, 0x1, 0x51af10)
        /root/work/src/github.com/araobp/nlan/common/state.go:32 +0x22c
main.main()
        /root/work/src/github.com/araobp/nlan/master.go:120 +0x1a4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 13 [IO wait]:
net.runtime_pollWait(0xb63f6bb8, 0x72, 0x10b0e090)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10b17db8, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10b17db8, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10b17d80, 0x10c0b000, 0x1000, 0x1000, 0x0, 0xb63f1030, 0x10b0e090)
        /root/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10b25810, 0x10c0b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/go/src/net/net.go:172 +0xc8
net/http.noteEOFReader.Read(0xb63f6cf0, 0x10b25810, 0x10b14cec, 0x10c0b000, 0x1000, 0x1000, 0x23977c, 0x0, 0x0)
        /root/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10bee780, 0x10c0b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10bec4b0)
        /root/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10bec4b0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10b14cc0)
        /root/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /root/go/src/net/http/transport.go:685 +0xab4

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0x10b14cc0)
        /root/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /root/go/src/net/http/transport.go:686 +0xad0
2015/12/29 17:58:22 /root/work/src/github.com/araobp/nlan/etc/ptn-bgp.yaml
2015/12/29 17:58:22 # iBGP/eBGP simulation
#
States:
  - Router: pe1
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe1w
              L2sw: l2swpe1w
            Links:
              LocalIp: {{.pe1}}
              RemoteIps: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.101/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.101/24
          - Id: access
            Nodes:
              Ptn: ptnpe1a
              L2sw: l2swpe1a
            Links:
              LocalIp: {{.pe1}}
              RemoteIps: [{{.ce1}}, {{.ce2}}]
            L2Vpn:
              - Vid: 11
                Vni: 111
                Peers: [{{.ce1}}]
                Ip: 10.201.11.1/24
              - Vid: 12
                Vni: 112
                Peers: [{{.ce2}}]
                Ip: 10.201.12.1/24
      Router:
        Loopback: 10.1.1.1/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.201.11.2
                RemoteAs: 1001
              - Peer: 10.201.12.2
                RemoteAs: 1002
  - Router: pe2
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe2w
              L2sw: l2swpe2w
            Links:
              LocalIp: {{.pe2}}
              RemoteIps: [{{.pe1}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.102/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe2}}, {{.pe3}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.102/24
          - Id: access
            Nodes:
              Ptn: ptnpe2a
              L2sw: l2swpe2a
            Links:
              LocalIp: {{.pe2}}
              RemoteIps: [{{.ce1}}, {{.ce2}}]
            L2Vpn:
              - Vid: 11
                Vni: 211
                Peers: [{{.ce1}}]
                Ip: 10.202.11.1/24
              - Vid: 12
                Vni: 212
                Peers: [{{.ce2}}]
                Ip: 10.202.12.1/24
      Router:
        Loopback: 10.1.1.2/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.202.11.2
                RemoteAs: 1001
              - Peer: 10.202.12.2
                RemoteAs: 1002
  - Router: pe3
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe3w
              L2sw: l2swpe3w
            Links:
              LocalIp: {{.pe3}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.1.103/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe4}}, {{.rr}}]
                Ip: 10.200.2.103/24
          - Id: access
            Nodes:
              Ptn: ptnpe3a
              L2sw: l2swpe3a
            Links:
              LocalIp: {{.pe3}}
              RemoteIps: [{{.ce3}}, {{.ce4}}]
            L2Vpn:
              - Vid: 13
                Vni: 313
                Peers: [{{.ce3}}]
                Ip: 10.203.13.1/24
              - Vid: 14
                Vni: 314
                Peers: [{{.ce4}}]
                Ip: 10.203.14.1/24
      Router:
        Loopback: 10.1.1.3/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.203.13.2
                RemoteAs: 1003
              - Peer: 10.203.14.2
                RemoteAs: 1004
  - Router: pe4
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnpe4w
              L2sw: l2swpe4w
            Links:
              LocalIp: {{.pe4}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
                Ip: 10.200.1.104/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.rr}}]
                Ip: 10.200.2.104/24
          - Id: access
            Nodes:
              Ptn: ptnpe4a
              L2sw: l2swpe4a
            Links:
              LocalIp: {{.pe4}}
              RemoteIps: [{{.ce3}}, {{.ce4}}]
            L2Vpn:
              - Vid: 13
                Vni: 413
                Peers: [{{.ce3}}]
                Ip: 10.204.13.1/24
              - Vid: 14
                Vni: 414
                Peers: [{{.ce4}}]
                Ip: 10.204.14.1/24
      Router:
        Loopback: 10.1.1.4/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.105
                RemoteAs: 100
                NextHopSelf: true
              - Peer: 10.204.13.2
                RemoteAs: 1003
              - Peer: 10.204.14.2
                RemoteAs: 1004
  - Router: rr
    Model:
      Ptn:
        Networks:
          - Id: wan
            Nodes:
              Ptn: ptnrrw
              L2sw: l2swrrw
            Links:
              LocalIp: {{.rr}}
              RemoteIps: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 101
                Vni: 1
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
                Ip: 10.200.1.105/24
              - Vid: 102
                Vni: 2
                Peers: [{{.pe1}}, {{.pe2}}, {{.pe3}}, {{.pe4}}]
                Ip: 10.200.2.105/24
      Router:
        Loopback: 10.1.1.5/32
        Bgp:
          - As: 100
            Neighbors:
              - Peer: 10.200.1.101
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.102
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.103
                RemoteAs: 100
                RouteReflectorClient: true
              - Peer: 10.200.1.104
                RemoteAs: 100
                RouteReflectorClient: true
  - Router: ce1
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce1a
              L2sw: l2swce1a
            Links:
              LocalIp: {{.ce1}}
              RemoteIps: [{{.pe1}}, {{.pe2}}]
            L2Vpn:
              - Vid: 1
                Vni: 111
                Peers: [{{.pe1}}]
                Ip: 10.201.11.2/24
              - Vid: 2
                Vni: 211
                Peers: [{{.pe2}}]
                Ip: 10.202.11.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.1.1/24
            Vhosts: 2
          - Network: 172.22.1.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.1/32
        Bgp:
          - As: 1001
            Neighbors:
              - Peer: 10.201.11.1
                RemoteAs: 100
              - Peer: 10.202.11.1
                RemoteAs: 100
  - Router: ce2
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce2a
              L2sw: l2swce2a
            Links:
              LocalIp: {{.ce2}}
              RemoteIps: [{{.pe1}}, {{.pe2}}]
            L2Vpn:
              - Vid: 1
                Vni: 112
                Peers: [{{.pe1}}]
                Ip: 10.201.12.2/24
              - Vid: 2
                Vni: 212
                Peers: [{{.pe2}}]
                Ip: 10.202.12.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.2.1/24
            Vhosts: 2
          - Network: 172.22.2.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.2/32
        Bgp:
          - As: 1002
            Neighbors:
              - Peer: 10.201.12.1
                RemoteAs: 100
              - Peer: 10.202.12.1
                RemoteAs: 100
  - Router: ce3
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce3a
              L2sw: l2swce3a
            Links:
              LocalIp: {{.ce3}}
              RemoteIps: [{{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 3
                Vni: 313
                Peers: [{{.pe3}}]
                Ip: 10.203.13.2/24
              - Vid: 4
                Vni: 413
                Peers: [{{.pe4}}]
                Ip: 10.204.13.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.3.1/24
            Vhosts: 2
          - Network: 172.22.3.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.3/32
        Bgp:
          - As: 1003
            Neighbors:
              - Peer: 10.203.13.1
                RemoteAs: 100
              - Peer: 10.204.13.1
                RemoteAs: 100
  - Router: ce4
    Model:
      Ptn:
        Networks:
          - Id: access
            Nodes:
              Ptn: ptnce4a
              L2sw: l2swce4a
            Links:
              LocalIp: {{.ce4}}
              RemoteIps: [{{.pe3}}, {{.pe4}}]
            L2Vpn:
              - Vid: 3
                Vni: 314
                Peers: [{{.pe3}}]
                Ip: 10.203.14.2/24
              - Vid: 4
                Vni: 414
                Peers: [{{.pe4}}]
                Ip: 10.204.14.2/24
      Vhosts:
        VhostProps:
          - Network: 172.21.4.1/24
            Vhosts: 2
          - Network: 172.22.4.1/24
            Vhosts: 2
      Router:
        Loopback: 10.1.2.4/32
        Bgp:
          - As: 1004
            Neighbors:
              - Peer: 10.203.14.1
                RemoteAs: 100
              - Peer: 10.204.14.1
                RemoteAs: 100
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xa03ac]

goroutine 1 [running]:
github.com/araobp/nlan/util.ListHosts(0x51ee01, 0x10bebee0)
        /root/work/src/github.com/araobp/nlan/util/etcd.go:78 +0x154
github.com/araobp/nlan/common.ReadState(0x10b256c8, 0x0, 0x1, 0x51af10)
        /root/work/src/github.com/araobp/nlan/common/state.go:32 +0x22c
main.main()
        /root/work/src/github.com/araobp/nlan/master.go:120 +0x1a4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 13 [IO wait]:
net.runtime_pollWait(0xb6383b98, 0x72, 0x10b0e090)
        /root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10b17db8, 0x72, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10b17db8, 0x0, 0x0)
        /root/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10b17d80, 0x10c0b000, 0x1000, 0x1000, 0x0, 0xb637e030, 0x10b0e090)
        /root/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10b25810, 0x10c0b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/go/src/net/net.go:172 +0xc8
net/http.noteEOFReader.Read(0xb6383cd0, 0x10b25810, 0x10b14ecc, 0x10c0b000, 0x1000, 0x1000, 0x23977c, 0x0, 0x0)
        /root/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10bee780, 0x10c0b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10bec4b0)
        /root/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10bec4b0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10b14ea0)
        /root/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /root/go/src/net/http/transport.go:685 +0xab4

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0x10b14ea0)
        /root/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /root/go/src/net/http/transport.go:686 +0xad0
```

**Comment by araobp** [comment]
In the case above, ListHosts() checks /nlan/ip. I manually set addresses:
```
$ etcdctl set /nlan/ip/pe1 10.10.10.1/24
$ etcdctl set /nlan/ip/pe2 10.10.10.2/24
$ etcdctl set /nlan/ip/pe3 10.10.10.3/24
$ etcdctl set /nlan/ip/pe4 10.10.10.4/24
$ etcdctl set /nlan/ip/rr 10.10.10.5/24
$ etcdctl set /nlan/ip/ce1 10.10.10.6/24
$ etcdctl set /nlan/ip/ce2 10.10.10.7/24
$ etcdctl set /nlan/ip/ce3 10.10.10.8/24
$ etcdctl set /nlan/ip/ce4 10.10.10.9/24
```

**Comment by araobp** [comment]
etcd.go does not seem to get those IP addresses, since returned map contains no data.
```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
main.main()
        /root/work/src/github.com/araobp/nlan/master.go:126 +0x2d0
```

**Comment by araobp** [comment]
The cause: ListHost() in etcd.go returns nil.

**Comment by araobp** [comment]
Bug
```
diff --git a/util/etcd.go b/util/etcd.go
index 56bcd8b..70ddc82 100644
--- a/util/etcd.go
+++ b/util/etcd.go
@@ -74,7 +74,7 @@ func ListHosts(secondary bool) map[string]interface{} {
        }
        list, err := kapi.Get(cont, key, &client.GetOptions{Recursive: true})
        hosts := make(map[string]interface{})
-       if err != nil {
+       if err == nil {
                nodes := list.Node.Nodes
                for _, node := range nodes {
                        path := strings.Split(node.Key, "/")
```
